#!/bin/bash

echo "=========================================="
echo "  🌍 地震分析系统 - 多平台部署助手"
echo "=========================================="
echo ""
echo "请选择部署平台："
echo ""
echo "  1) 腾讯云 Webify (国内推荐，免费)"
echo "  2) 阿里云 OSS (国内推荐，低成本)"
echo "  3) 阿里云学生机 (长期运行，10元/月)"
echo "  4) Vercel + Render (海外推荐，免费)"
echo "  5) Gitee Pages (国内免费)"
echo "  6) Zeabur (新兴平台，免费)"
echo "  7) 内网穿透 (临时演示)"
echo ""
read -p "请输入选项 [1-7]: " choice

case $choice in
  1)
    echo ""
    echo "📦 腾讯云 Webify 部署步骤："
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "1. 访问: https://webify.cloudbase.net"
    echo "2. 用微信扫码登录"
    echo "3. 点击「新建应用」→「导入Git仓库」"
    echo "4. 选择你的GitHub/Gitee仓库"
    echo "5. 配置构建命令: cd frontend && npm install && npm run build"
    echo "6. 配置输出目录: frontend/dist"
    echo "7. 点击「部署」"
    echo ""
    echo "✅ 完全免费，国内访问快！"
    ;;
  2)
    echo ""
    echo "📦 阿里云 OSS 部署步骤："
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "1. 访问: https://oss.console.aliyun.com"
    echo "2. 创建Bucket (公共读)"
    echo "3. 配置静态网站托管"
    echo "4. 上传frontend/dist目录"
    echo ""
    echo "💰 费用: 约1-5元/月"
    echo ""
    echo "正在构建前端..."
    cd ../frontend && npm install && npm run build
    echo "✅ 构建完成！请手动上传dist目录到OSS"
    ;;
  3)
    echo ""
    echo "📦 阿里云学生机部署步骤："
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "1. 访问: https://university.aliyun.com"
    echo "2. 完成学生认证"
    echo "3. 购买学生机 (9.5元/月起)"
    echo "4. 连接服务器后运行以下命令："
    echo ""
    echo "   curl -fsSL https://get.docker.com | bash"
    echo "   git clone https://github.com/your-username/earthquake-system.git"
    echo "   cd earthquake-system/deploy"
    echo "   docker-compose up -d"
    echo ""
    echo "💰 费用: 9.5元/月"
    ;;
  4)
    echo ""
    echo "📦 Vercel + Render 部署步骤："
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "【后端 - Render】"
    echo "1. 访问: https://render.com"
    echo "2. New Web Service → 选择仓库"
    echo "3. Environment: Python 3"
    echo "4. Build: pip install -r requirements.txt"
    echo "5. Start: python app.py"
    echo ""
    echo "【前端 - Vercel】"
    echo "1. 访问: https://vercel.com"
    echo "2. New Project → 选择仓库"
    echo "3. Root Directory: frontend"
    echo "4. 自动检测Vue.js"
    echo ""
    echo "✅ 完全免费！"
    ;;
  5)
    echo ""
    echo "📦 Gitee Pages 部署步骤："
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "1. 访问: https://gitee.com"
    echo "2. 创建仓库并推送代码"
    echo "3. 服务 → Gitee Pages"
    echo "4. 选择分支和frontend/dist目录"
    echo "5. 启动"
    echo ""
    echo "正在构建前端..."
    cd ../frontend && npm install && npm run build
    echo "✅ 构建完成！"
    ;;
  6)
    echo ""
    echo "📦 Zeabur 部署步骤："
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "1. 访问: https://zeabur.com"
    echo "2. 用GitHub登录"
    echo "3. New Project"
    echo "4. 添加Python服务（后端）"
    echo "5. 添加Static服务（前端）"
    echo "6. 一键部署"
    echo ""
    echo "✅ 完全免费，支持中文！"
    ;;
  7)
    echo ""
    echo "📦 内网穿透部署："
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "【方式一：ngrok】"
    echo "1. 访问 https://ngrok.com 注册"
    echo "2. 下载ngrok"
    echo "3. 运行: ngrok http 8090"
    echo ""
    echo "【方式二：Cloudflare Tunnel】"
    echo "1. 安装cloudflared"
    echo "2. 运行: cloudflared tunnel --url http://localhost:8090"
    echo ""
    echo "✅ 适合临时演示！"
    ;;
  *)
    echo "无效选项"
    ;;
esac

echo ""
echo "=========================================="
echo "  详细文档: deploy/MORE_OPTIONS.md"
echo "=========================================="
